INSERT INTO Automoveis (id, placa, marca, cor) VALUES
(1, LOWER('ABC1234'), LOWER('Toyota'), LOWER('Azul')),
(2, LOWER('DEF5678'), LOWER('Honda'), LOWER('Vermelho')),
(3, LOWER('GHI9012'), LOWER('Ford'), LOWER('Preto')),
(4, LOWER('JKL3456'), LOWER('Chevrolet'), LOWER('Branco')),
(5, LOWER('MNO7890'), LOWER('Hyundai'), LOWER('Prata')),
(6, LOWER('PQR1234'), LOWER('BMW'), LOWER('Preto')),
(7, LOWER('STU5678'), LOWER('Mercedes'), LOWER('Azul')),
(8, LOWER('VWX9012'), LOWER('Audi'), LOWER('Vermelho')),
(9, LOWER('YZA3456'), LOWER('Porsche'), LOWER('Branco')),
(10, LOWER('BCD7890'), LOWER('Lamborghini'), LOWER('Amarelo')),
(11, LOWER('EFG1234'), LOWER('Ferrari'), LOWER('Vermelho')),
(12, LOWER('HIJ5678'), LOWER('Maserati'), LOWER('Azul')),
(13, LOWER('KLM9012'), LOWER('Aston Martin'), LOWER('Preto')),
(14, LOWER('NOP3456'), LOWER('Bugatti'), LOWER('Branco')),
(15, LOWER('QRS7890'), LOWER('McLaren'), LOWER('Prata')),
(16, LOWER('TUV1234'), LOWER('Bentley'), LOWER('Azul')),
(17, LOWER('WXY5678'), LOWER('Rolls-Royce'), LOWER('Preto')),
(18, LOWER('ZAB9012'), LOWER('Jaguar'), LOWER('Vermelho')),
(19, LOWER('CDE3456'), LOWER('Land Rover'), LOWER('Branco')),
(20, LOWER('FGH7890'), LOWER('Jeep'), LOWER('Prata'));