INSERT INTO Automoveis (placa, marca, cor) VALUES
(LOWER('ABC1234'), LOWER('Toyota'), LOWER('Azul')),
(LOWER('DEF5678'), LOWER('Honda'), LOWER('Vermelho')),
(LOWER('GHI9012'), LOWER('Ford'), LOWER('Preto')),
(LOWER('JKL3456'), LOWER('Chevrolet'), LOWER('Branco')),
(LOWER('MNO7890'), LOWER('Hyundai'), LOWER('Prata')),
(LOWER('PQR1234'), LOWER('BMW'), LOWER('Preto')),
(LOWER('STU5678'), LOWER('Mercedes'), LOWER('Azul')),
(LOWER('VWX9012'), LOWER('Audi'), LOWER('Vermelho')),
(LOWER('YZA3456'), LOWER('Porsche'), LOWER('Branco')),
(LOWER('BCD7890'), LOWER('Lamborghini'), LOWER('Amarelo')),
(LOWER('EFG1234'), LOWER('Ferrari'), LOWER('Vermelho')),
(LOWER('HIJ5678'), LOWER('Maserati'), LOWER('Azul')),
(LOWER('KLM9012'), LOWER('Aston Martin'), LOWER('Preto')),
(LOWER('NOP3456'), LOWER('Bugatti'), LOWER('Branco')),
(LOWER('QRS7890'), LOWER('McLaren'), LOWER('Prata')),
(LOWER('TUV1234'), LOWER('Bentley'), LOWER('Azul')),
(LOWER('WXY5678'), LOWER('Rolls-Royce'), LOWER('Preto')),
(LOWER('ZAB9012'), LOWER('Jaguar'), LOWER('Vermelho')),
(LOWER('CDE3456'), LOWER('Land Rover'), LOWER('Branco')),
(LOWER('FGH7890'), LOWER('Jeep'), LOWER('Prata'));