version: '3.0'

volumes:
    db:

services:
    backend:
        container_name: backend
        build: .
        ports:
            - 8000:8000
        platform: linux/x86_64
        restart: always
        depends_on:
            db:
                condition: service_started
        networks:
            - network
        healthcheck:
            test: ['CMD', 'lsof', '-t', '-i:8000']
            timeout: 30s
            retries: 5
    db:
        image: postgres:15.5-alpine
        container_name: db
        restart: always
        user: postgres
        environment:
            POSTGRES_DB: ${PGSQL_NAME}
            POSTGRES_USER: ${PGSQL_USER}
            POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready-U ${PGSQL_USER}']
            interval: 30s
            timeout: 10s
            retries: 3

networks:
    network:
        driver: bridge
