name: Node.js CI

on:
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Verificando o repositório do Github
              uses: actions/checkout@v4

            - name: Use Node.js 20.9.0
              uses: actions/setup-node@v4
              with:
                  node-version: 20.9.0

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Executing lint
              run: pnpm run lint
            - name: Executing test
              run: pnpm run test
